spring:
  datasource:
    url: jdbc:mysql://192.168.140.160:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: qwer1234
    filters: wall,mergeStat
